from .global_architectures import FeedForwardNN
from .global_architectures import FullGraphNetwork
from .global_architectures import FullGraphSiameseNetwork
from .global_architectures import FullGraphMultiTaskNetwork
from .global_architectures import TaskHeads
from .dgl_architectures import FeedForwardDGL
from .pyg_architectures import FeedForwardPyg
