from .global_architectures import FeedForwardNN
from .global_architectures import FullGraphNetwork
from .global_architectures import FullGraphMultiTaskNetwork
from .global_architectures import TaskHeads
from .pyg_architectures import FeedForwardPyg
