- name: Dom
  email: dominique@invivoai.com
  num_commits: 101
  first_commit: 2021-01-20 01:31:50
  github: invivoai
  alternate_emails:
  - ubuntu@ip-172-31-21-253.us-east-2.compute.internal
  - ubuntu@ip-172-31-29-17.us-east-2.compute.internal
  - ubuntu@ip-172-31-28-104.us-east-2.compute.internal
  - ubuntu@ip-172-31-30-152.us-east-2.compute.internal
  - 47570400+DomInvivo@users.noreply.github.com
  aliases:
  - Ubuntu
  - Dominique
  - DomInvivo
- name: Hadrien Mary
  email: hadrien.mary@gmail.com
  alternate_emails:
  - hadim@users.noreply.github.com
  num_commits: 4
  first_commit: 2021-01-20 10:31:10
  aliases:
  - hadim
  github: invivoai
- name: Ubuntu
  email: ubuntu@ip-172-31-19-91.us-east-2.compute.internal
  num_commits: 9
  first_commit: 2021-03-23 12:26:32
- name: Therence1
  email: 38595485+Therence1@users.noreply.github.com
  num_commits: 1
  first_commit: 2021-03-21 11:41:43
  github: Therence1
- name: Hannes Stärk
  email: hannes.staerk@gmail.com
  alternate_emails:
  - 32128654+HannesStark@users.noreply.github.com
  num_commits: 4
  first_commit: 2021-03-29 05:30:23
- name: alip67
  email: alip67@users.noreply.github.com
  num_commits: 1
  first_commit: 2021-06-10 11:27:50
- name: Dominique
  email: dominique@valencediscovery.com
  num_commits: 40
  first_commit: 2021-05-31 21:23:27
- name: Ali
  email: feraktal@yahoo.com
  num_commits: 2
  first_commit: 2021-06-18 10:13:43
- name: Gabriela Moisescu-Pareja
  email: gabriela@valencediscovery.com
  num_commits: 5
  first_commit: 2021-12-23 12:01:17
  github: graphriela
