# Testing the gin model with the PCQMv2 dataset on IPU.

defaults:
  - base_config: small
  - _self_

constants:
  name: neurips2023_small_data_gin

architecture:
  gnn:  # Set as null to avoid a post-nn network
    layer_type: 'pyg:gin'
