# Testing the gcn model with the toymix dataset on IPU.

defaults:
  - base_config: small
  - _self_

constants:
  name: neurips2023_small_data_gcn

architecture:
  gnn:  # Set as null to avoid a post-nn network
    layer_type: 'pyg:gcn' #pyg:gine #'pyg:gps' # pyg:gated-gcn, pyg:gine,pyg:gps
