# @package _global_

architecture:
  task_heads:
    homolumo:
      task_level: graph
      out_dim: 1
      hidden_dims: 256
      depth: 2                          # Not needed if we have hidden_dims
      activation: relu
      last_activation: none
      dropout: 0.18
      normalization: layer_norm
      last_normalization: "none"
      residual_type: none
