# Testing the mpnn only model with the PCQMv2 dataset on IPU.

defaults:
 - base_config: small

constants:
  name: neurips2023_small_data_mpnn

architecture:
  pre_nn_edges:   # Set as null to avoid a pre-nn network
    out_dim: 32
    hidden_dims: 128
    depth: 2
    activation: relu
    last_activation: none
    dropout: ${architecture.pre_nn.dropout}
    normalization: ${architecture.pre_nn.normalization}
    last_normalization: ${architecture.pre_nn.normalization}
    residual_type: none

  gnn:  # Set as null to avoid a post-nn network
    out_dim: &gnn_dim 64
    hidden_dims: *gnn_dim
    layer_type: 'pyg:gps' #pyg:gine #'pyg:gps' # pyg:gated-gcn, pyg:gine,pyg:gps
    layer_kwargs:  # Parameters for the model itself. You could define dropout_attn: 0.1
      mpnn_type: 'pyg:mpnnplus'
      out_dim_edges: 32
