# Testing the gine model with the PCQMv2 dataset on IPU.

defaults:
  - base_config: small
  - _self_

constants:
  name: neurips2023_small_data_gine

architecture:
  pre_nn_edges:   # Set as null to avoid a pre-nn network
    out_dim: 32
    hidden_dims: 128
    depth: 2
    activation: relu
    last_activation: none
    dropout: ${architecture.pre_nn.dropout}
    normalization: ${architecture.pre_nn.normalization}
    last_normalization: ${architecture.pre_nn.normalization}
    residual_type: none

  gnn:  # Set as null to avoid a post-nn network
    layer_type: 'pyg:gine' #pyg:gine #'pyg:gps' # pyg:gated-gcn, pyg:gine,pyg:gps