# @package _global_

#Task-specific
predictor:
  metrics_on_progress_bar:
    # All below metrics are directly copied from the TDC website.
    # For more information, see https://tdcommons.ai/benchmark/admet_group/overview/
    caco2_wang: ["mae"]
    hia_hou: ["auroc"]
    pgp_broccatelli: ["auroc"]
    bioavailability_ma: ["auroc"]
    lipophilicity_astrazeneca: ["mae"]
    solubility_aqsoldb: ["mae"]
    bbb_martins: ["auroc"]
    ppbr_az: ["mae"]
    vdss_lombardo: ["spearman"]
    cyp2d6_veith: ["auprc"]
    cyp3a4_veith: ["auprc"]
    cyp2c9_veith: ["auprc"]
    cyp2d6_substrate_carbonmangels: ["auprc"]
    cyp3a4_substrate_carbonmangels: ["auprc"]
    cyp2c9_substrate_carbonmangels: ["auprc"]
    half_life_obach: ["spearman"]
    clearance_microsome_az: ["spearman"]
    clearance_hepatocyte_az: ["spearman"]
    herg: ["auroc"]
    ames: ["auroc"]
    dili: ["auroc"]
    ld50_zhu: ["auroc"]
  loss_fun:
    caco2_wang: mae
    hia_hou: bce
    pgp_broccatelli: bce
    bioavailability_ma: bce
    lipophilicity_astrazeneca: mae
    solubility_aqsoldb: mae
    bbb_martins: bce
    ppbr_az: mae
    vdss_lombardo: mae
    cyp2d6_veith: bce
    cyp3a4_veith: bce
    cyp2c9_veith: bce
    cyp2d6_substrate_carbonmangels: bce
    cyp3a4_substrate_carbonmangels: bce
    cyp2c9_substrate_carbonmangels: bce
    half_life_obach: mae
    clearance_microsome_az: mae
    clearance_hepatocyte_az: mae
    herg: bce
    ames: bce
    dili: bce
    ld50_zhu: mae
  random_seed: ${constants.seed}
  optim_kwargs:
    lr: 4.e-5 # warmup can be scheduled using torch_scheduler_kwargs
  torch_scheduler_kwargs:
    module_type: WarmUpLinearLR
    max_num_epochs: &max_epochs 10
    warmup_epochs: 10
    verbose: False
  target_nan_mask: null # null: no mask, 0: 0 mask, ignore-flatten, ignore-mean-per-label
  multitask_handling: flatten # flatten, mean-per-label

# Task-specific
metrics:
  caco2_wang: &regression_metrics
    - name: mae
      metric: mae
      target_nan_mask: null
      multitask_handling: flatten
      threshold_kwargs: null
    - name: spearman
      metric: spearmanr
      threshold_kwargs: null
      target_nan_mask: null
      multitask_handling: mean-per-label
    - name: pearson
      metric: pearsonr
      threshold_kwargs: null
      target_nan_mask: null
      multitask_handling: mean-per-label
    - name: r2_score
      metric: r2_score
      target_nan_mask: null
      multitask_handling: mean-per-label
      threshold_kwargs: null
  hia_hou: &classification_metrics
    - name: auroc
      metric: auroc
      task: binary
      multitask_handling: mean-per-label
      threshold_kwargs: null
    - name: auprc
      metric: averageprecision
      task: binary
      multitask_handling: mean-per-label
      threshold_kwargs: null
    - name: accuracy
      metric: accuracy
      multitask_handling: mean-per-label
      target_to_int: True
      average: micro
      threshold_kwargs: &threshold_05
        operator: greater
        threshold: 0.5
        th_on_preds: True
        th_on_target: True
    - name: mcc
      metric: mcc
      num_classes: 2
      multitask_handling: mean-per-label
      target_to_int: True
      average: micro
      threshold_kwargs: *threshold_05
  pgp_broccatelli: *classification_metrics
  bioavailability_ma: *classification_metrics
  lipophilicity_astrazeneca: *regression_metrics
  solubility_aqsoldb: *regression_metrics
  bbb_martins: *classification_metrics
  ppbr_az: *regression_metrics
  vdss_lombardo: *regression_metrics
  cyp2d6_veith: *classification_metrics
  cyp3a4_veith: *classification_metrics
  cyp2c9_veith: *classification_metrics
  cyp2d6_substrate_carbonmangels: *classification_metrics
  cyp3a4_substrate_carbonmangels: *classification_metrics
  cyp2c9_substrate_carbonmangels: *classification_metrics
  half_life_obach: *regression_metrics
  clearance_microsome_az: *regression_metrics
  clearance_hepatocyte_az: *regression_metrics
  herg: *classification_metrics
  ames: *classification_metrics
  dili: *classification_metrics
  ld50_zhu: *regression_metrics

datamodule:
  module_type: "ADMETBenchmarkDataModule"
  args:
    # TDC specific
    tdc_benchmark_names: null
    tdc_train_val_seed: ${constants.seed}
