# Testing the gin model with the PCQMv2 dataset on IPU.
constants:
  name: &name neurips2023_small_data_gin
  config_override: "expts/neurips2023_configs/baseline/config_small_gcn_baseline.yaml"
  seed: &seed 1000

architecture:
  gnn:  # Set as null to avoid a post-nn network
    in_dim: 64 # or otherwise the correct value
    out_dim: &gnn_dim 96
    hidden_dims: *gnn_dim
    layer_type: 'pyg:gin' #pyg:gine #'pyg:gps' # pyg:gated-gcn, pyg:gine,pyg:gps

trainer:
  seed: *seed
  logger:
    name: *name
    project: *name
  model_checkpoint:
    dirpath: models_checkpoints/neurips2023-small-gin/
    filename: *name
